field.formatter.settings.audio_embed_field_thumbnail:
  type: mapping
  label: 'Thumbnail formatter settings.'
  mapping:
    image_style:
      type: string
      label: 'Image Style'
    link_image_to:
      type: string
      label: 'Link image to'

field.formatter.settings.audio_embed_field_audio:
  type: mapping
  label: 'Audio formatter settings.'
  mapping:
    autoplay:
      type: boolean
      label: 'Autoplay'
    responsive:
      type: boolean
      label: 'Responsive'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'

field.formatter.settings.audio_embed_field_colorbox:
  type: mapping
  label: 'Colorbox formatter settings.'
  mapping:
    autoplay:
      type: boolean
      label: 'Autoplay'
    responsive:
      type: boolean
      label: 'Responsive'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'
    image_style:
      type: string
      label: 'Image Style'
    link_image_to:
      type: string
      label: 'Link image to'
    modal_max_width:
      type: integer
      label: 'Modal max width'

field.field_settings.audio_embed_field:
  type: mapping
  label: 'Audio field settings.'
  mapping:
    allowed_providers:
      type: sequence
      label: 'Allowed Providers'
      sequence:
        type: string
